n = input("Display multiplication table of? ")
x = int(n)
print(x,'x',1,'=',x*1)
print(x,'x',2,'=',x*2)
print(x,'x',3,'=',x*3)
print(x,'x',4,'=',x*4)
print(x,'x',5,'=',x*5)
print(x,'x',6,'=',x*6)

i = input("Display multiplication table of? ")
q = int(n)
print(q,'x',1,'=',q*1)
print(q,'x',2,'=',q*2)
print(q,'x',3,'=',q*3)
print(q,'x',4,'=',q*4)
print(q,'x',5,'=',q*5)
print(q,'x',6,'=',q*6)