x= int(intput())

print("Display multiplication table of? "x)

print(x,'x','1','=',x*1)
print(x,'x','2','=',x*2)
print(x,'x','3','=',x*3)
print(x,'x','4','=',x*4)
print(x,'x','5','=',x*5)
print(x,'x','6','=',x*6)
print(x,'x','7','=',x*7)
print(x,'x','8','=',x*8)
print(x,'x','9','=',x*9)
print(x,'x','10','=',x*10)
print(x,'x','11','=',x*11)
print(x,'x','12','=',x*12)