n = input("enter num : ")
x = int(n)
print(x, '*', 1 ,'=', x * 1)
print(x, '*', 2 ,'=', x * 1)
print(x, '*', 3 ,'=', x * 1)
print(x, '*', 4 ,'=', x * 1)
print(x, '*', 5 ,'=', x * 1)
print(x, '*', 6 ,'=', x * 1)