n = input("Display multiplication table of? 12")
x = int(n)
print(x,'*',1,'=',x*1)
print(x,'*',2,'=',x*2)
print(x,'*',1,'=',x*3)
print(x,'*',1,'=',x*4)
print(x,'*',1,'=',x*5)
print(x,'*',2,'=',x*6)

n = input("Display multiplication table of? 12")
x = int(n)
print(x,'*',1,'=',x*1)
print(x,'*',2,'=',x*2)
print(x,'*',1,'=',x*3)
print(x,'*',1,'=',x*4)
print(x,'*',1,'=',x*5)
print(x,'*',2,'=',x*6)