n = input("Display multiplication table of? ")
x = int(n)
print(x,'x',1,'=',x*1)
print(x,'x',2,'=',x*2)
print(x,'x',1,'=',x*3)
print(x,'x',1,'=',x*4)
print(x,'x',1,'=',x*5)
print(x,'x',2,'=',x*6)

n = input("Display multiplication table of? ")
q = int(n)
print(q,'x',1,'=',x*1)
print(q,'x',2,'=',x*2)
print(q,'x',1,'=',x*3)
print(q,'x',1,'=',x*4)
print(q,'x',1,'=',x*5)
print(q,'x',2,'=',x*6)