n = int(input("Display multiplication table of? "))
print('n','x',1,'=',n*1)
print('n','x',2,'=',n*2)
print('n','x',3,'=',n*3)
print('n','x',4,'=',n*4)
print('n','x',5,'=',n*5)
print('n','x',6,'=',n*6)