n = input("Enter Number :")
x = int(n)
print(x ,'x' ,1 , '=',x*1 )
print(x ,'x' ,2 , '=',x*2 )
print(x ,'x' ,1 , '=',x*3 )
print(x ,'x' ,2 , '=',x*4 )
print(x ,'x' ,1 , '=',x*5 )
print(x ,'x' ,2 , '=',x*6 )