xt = input("Display multiplication table of?:")
  x = int(xt)
  print(x,'*',1,'=',x*1)
  print(x,'*',2,'=',x*2)
  print(x,'*',3,'=',x*3)
  print(x,'*',4,'=',x*4)
  print(x,'*',5,'=',x*5)
  print(x,'*',6,'=',x*6)