x = input("x:")
y = input("y:")
x = int(x)
y = int(y)
print("Display multiplication table of? ",x)
print(x*1)
print(x*2)
print(x*3)
print(x*4)
print(x*5)
print(x*6)
print("Display multiplication table of? ",y)
print(y*1)
print(y*2)
print(y*3)
print(y*4)
print(y*5)
print(y*6)