print("Display multiplication table of? 12")
x = input("Enter x:")
x = int(x)
print(x,'x',1,"=",x*1)
print(x,'x',2,"=",x*2)
print(x,'x',3,"=",x*3)
print(x,'x',4,"=",x*4)
print(x,'x',5,"=",x*5)
print(x,'x',6,"=",x*6)