x = int(input("Display multiplication table of? "))
print(f"{x} * 1 = {x*1}")
print(f"{x} * 2 = {x*2}")
print(f"{x} * 3 = {x*3}")
print(f"{x} * 4 = {x*4}")
print(f"{x} * 5 = {x*5}")
print(f"{x} * 6 = {x*6}")