num = input("Display multiplication table of?")
num = int(num)
print(num,"x",1"=",num*1)
print(num,"x",2"=",num*2)
print(num,"x",3"=",num*3)
print(num,"x",4"=",num*4)
print(num,"x",5"=",num*5)
print(num,"x",6"=",num*6)