#print('Hello Python!')
num = input("Display multiplication table of?: ")
X = int(num)
print(X,"x",1,"=",x*1)
print(X,"x",2,"=",x*2)
print(X,"x",3,"=",x*3)
print(X,"x",4,"=",x*4)
print(X,"x",5,"=",x*5)
print(X,"x",6,"=",x*6)