num = int(input("Display multiplication table of? "))
print(num,'x', 1, '=',num * 1)
print(num,'x', 2, '=',num * 1)
print(num,'x', 3, '=',num * 1)
print(num,'x', 4, '=',num * 1)
print(num,'x', 5, '=',num * 1)
print(num,'x', 6, '=',num * 1)