price = input("Enter product price:")
price = float(price)
point = input("Enter your point:")
point = int(point)
Discount = input("Discount:")
Discount = 1/500*float(Discount)
print(f"Total price : {price:.2f}")
print(f"Total Discount : {Discount:.2f}")
print(f"Total: {price-Discount:.2f}")