num1= input("Enter product price :")
num2= input("Enter product point :")
num1 = float(num1)
num2 = int(num2)
num3 = 1/500*float(num1)
num4 =int(num1)-int(num3)
print (f"Discount: {num3:.2f}")
print (f"total :{num4:.2f}")