price = input("Enter product price:") 
point = input("Enter your point:") 
pirce = float(price)
point = int(point)
Discount = 1/500*int(point)
print("Enter product price:""%.2f" % price)
print("Enter your point:""%.2f" % point)
print("Discount: ""%.2f" % Discount)
final_price = float(pirce)-float(Discount)
print("Total: ""%.2f" % final_price)