num1 = input("Enter price: ")
num2 = input("Enter point:")
num1 = float (num1)
num2 = float (num2)
num3 = 1/500 * float(num2)
num4 = int (num1)-float(num3)
print (f"Discount : {num3:.2f}")
print (f"Total : {num4:.2f} baht")