_v1= input("enter v1(space-seperated):")
_v2 = input("enter v2(space-seperated):")
v1 = _v1.split(' ')
v2 =_v2.split(' ')
dotproduct =(int(v1[0])*int(v2[0]))+(int(v1[1])*int(v2[1]))+(int(v1[2])*int(v2[2]))
print(f"dotproduct:{dotproduct}")