price = input("Enter price")
price = float(price)
point = input("Enter point")
point = float(point)
discount = point/500
discount = float(discount)
Total = (price - discount)
print(Total)
print("Your discount : %.2f" % discount)
print("price %.2f baht = %.2f discount" % (price,discount))
print(f"price {price:.2f} baht = {discount:.2f} discount")