price=input("Enter product price: ")
point=input("Enter your point: ")
price=float(price)
Discount=(float(point)/500)
total=(price-Discount)
print(f"Discount: {discount:.2f}")
print(f"Total: {total:.2f} Baht")