fises = input("Enter v1 (space-separated):")
two = input("Enter v2 (space-separated):")
fist = fises.split("")
two = twos.split("")
frist[0] = int(frist[0])
frist[1] = int(frist[1])
frist[2] = int(frist[2])
print(frist)
two[0] = int(two[0])
two[1] = int(two[1])
two[2] = int(two[2])         
print(two)