print('p    y    t    h    o    n')
print('p                        p')
print('y                        y')
print('t                        t')
print('h                        h')
print('o                        o')
print('n                        n')
print('p    y    t     h    o    n')