x = input()
split_x = x.split(",")
print(int(split_x[0])+int(split_x[1]))
print(int(split_x[0])-int(split_x[1]))
print(int(split_x[0])*int(split_x[1]))
print(int(split_x[0])/int(split_x[1]))
print(int(split_x[0])//int(split_x[1]))
print(int(split_x[0])%int(split_x[1]))
print(int(split_x[0])**int(split_x[1]))