x = input('KK').split(',')
y = int(x[0])
z = int(x[1])
print(x[0,'+',x[1],'=',z+y,sep=''])
print(x[0,'-',x[1],'=',z-y,sep=''])
print(x[0,'*',x[1],'=',z*y,sep=''])
print(x[0,'/',x[1],'=',z/y,sep=''])
print(x[0,'//',x[1],'=',z//y,sep=''])
print(x[0,'%',x[1],'=',z%y,sep=''])
print(x[0,'**',x[1],'=',z**y,sep=''])