x=input()
y=x.slit(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')
x=input()
y=x.slit(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')
x=input()
y=x.slit(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')