x = input("")
y = split_char=x.split(',')
A = int(y[0])
B = int(y[1])
print(A,'+',B,'=',A+B)
print(A,'-',B,'=',A-B)
print(A,'*',B,'=',A*B)
print(A,'//',B,'=',A/B)
print(A,'%',B,'=',A%B)
print(A,'**',B,'=',A**B)