x,y = input()
print("x+y=",int(x)+int(y))
print("x-y=",int(x)-int(y))
print("x*y=",int(x)*int(y))
print("x/y=",int(x)/int(y))
print("x//y=",int(x)//int(y))
print("x%y=",int(x)%int(y))
print("x**y=",int(x)**int(y))