input_str = input()
num_str = input_str.split(',')
num1 = int(num_str[0])
num2 = int(num_str[1])
sum = num1+num2
minus = num1-num2
multiply = num1*num2
divide = num1/num2
ddivine = num1//num2
per = num1%num2
doubemul = num1**num2
print("{0}+{1}={2}".format(num1,num2,sum))
print("{0}-{1}={2}".format(num1,num2,minus))
print("{0}*{1}={2}".format(num1,num2,multiply))
print("{0}/{1}={2}".format(num1,num2,divide))
print("{0}//{1}={2}".format(num1,num2,ddivine))
print("{0}%{1}={2}".format(num1,num2,per))
print("{0}**{1}={2}".format(num1,num2,doubemul))