x,y = input().split(",")
b,a = input().split(",")
print("1+2=",int(x)+int(y))
print("1-2=",int(x)-int(y))
print("1*2=",int(x)*int(y))
print("1/2=",int(x)/int(y))
print("1//2=",int(x)//int(y))
print("1%2=",int(x)%int(y))
print("1**2=",int(x)**int(y))

print("-7+2=",int(b)+int(a))
print("-7-2=",int(b)-int(a))
print("-7*2=",int(b)*int(a))
print("-7/2=",int(b)/int(a))
print("-7//2=",int(b)//int(a))
print("-7%2=",int(b)%int(a))
print("-7**2=",int(b)**int(a))