x,y,a,b = input().split(",")
print("1+2=",int(x)+int(y))
print("1-2=",int(x)-int(y))
print("1*2=",int(x)*int(y))
print("1/2=",int(x)/int(y))
print("1//2=",int(x)//int(y))
print("1%2=",int(x)%int(y))
print("1**2=",int(x)**int(y))

print("-7+2=",int(a)+int(b))
print("-7-2=",int(a)-int(b))
print("-7*2=",int(a)*int(b))
print("-7/2=",int(a)/int(b))
print("-7//2=",int(a)//int(b))
print("-7%2=",int(a)%int(b))
print("-7**2=",int(a)**int(b))