x,y, = input().split(",")
print("1+2=",int(x)+int(y))
print("1-2=",int(x)-int(y))
print("1*2=",int(x)*int(y))
print("1/2=",int(x)/int(y))
print("1//2=",int(x)//int(y))
print("1%2=",int(x)%int(y))
print("1**2=",int(x)**int(y))