input_str = input()
num_str = input_str.split(',')
num1 = int(num_str[0])
num2 = int(num_str[1])
sum = num1+num2
minus = num1-num2
multiply = num1*num2
divide = num1/num2
ddivine = num1//num2
per = num1%num2
doubemul = num1**num2
print(num1+num2=sum)
print(num1-num2=minus)
print(num1*num2=multiply)
print(num1/num2=divide)
print(num1//num2=ddivide)
print(num1%num2=per)
print(num1**num2=doublemul)