x=input()
y=x.split(',')
print(f'sum is {int(y[0])+int(y[1])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[1])-int(y[0])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[0])*int(y[1])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[0])/int(y[1])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[0])//int(y[1])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[0])%int(y[1])}')
x=input()
y=x.split(',')
print(f'sum is {int(y[0])**int(y[1])}')