x = input
x = x.split(",")
x = input()
x = x.split(",")
print("sum is:",int(x[0])+int(x[1]))
print("sum is:",int(x[0])-int(x[1]))
print("sum is:",int(x[0])*int(x[1]))
print("sum is:",int(x[0])/int(x[1]))
print("sum is:",int(x[0])//int(x[1]))
print("sum is:",int(x[0])%int(x[1]))
print("sum is:",int(x[0])**int(x[1]))