print("Test case 1")
number=input('input:\n')
print("Output:\n",number)
print("Test case 2")
number2=input('input:\n')
print("Output:\n:",number2)
print("Test case 1")
i=input('input:\n')
print("Output:\n",i)