x = input().split(',')
print("sum is",(x[0])+(x[1]))
print("sum is",(x[0])-(x[1]))
print("sum is",(x[0])*(x[1]))
print("sum is",(x[0])/(x[1]))
print("sum is",(x[0])//(x[1]))
print("sum is",(x[0])//(x[1]))
print("sum is",(x[0])%(x[1])))
print("sum is",(x[0])**(x[1])))