number = input()
split_char=number.spliit(',')
print((split_char[0])+int(split_char[1]))
print((split_char[0])-int(split_char[2]))
print((split_char[0])*int(split_char[2]))
print((split_char[0])/int(split_char[2]))
print((split_char[0])//int(split_char[2]))
print((split_char[0])%int(split_char[2]))
print((split_char[0])**int(split_char[2]))