number = int(input("enter your number"))
split_char=number.spliit(',')
print((split_char[0])+(split_char[1]))
print((split_char[0])-(split_char[1]))
print((split_char[0])*(split_char[1]))
print((split_char[0])/(split_char[1]))
print((split_char[0])//(split_char[1]))
print((split_char[0])%(split_char[1]))
print((split_char[0])**(split_char[1]))