x1 = int(input('Enter x-coordinate of point 1:'))
y1 = int(input('Enter y-coordinate of point 1:'))
x2 = int(input('Enter x-coordinate of point 2:'))
y2 = int(input('Enter y-coordinate of point 2:'))
slope = (y2+y1)-(x2+x1)
print('The distance between the two points is: ',slope)