x = input('Enter a series of numbers separated by commas: ')
xs = x.split(",")
xs[0] = int(xs[0])
xs[1] = int(xs[1])
xs[2] = int(xs[2])
xs[3] = int(xs[3])
xs[4] = int(xs[4])

x_min = min(xs)
x_max = max(xs)

r0 = (xs[0] - x_min) / (x_max - x_min)
r1 = (xs[1] - x_min) / (x_max - x_min)
r2 = (xs[2] - x_min) / (x_max - x_min)
r3 = (xs[3] - x_min) / (x_max - x_min)
r4 = (xs[4] - x_min) / (x_max - x_min)

print('Normalized values: ')
print('%.2f'%r0)
print('%.2f'%r1)
print('%.2f'%r2)
print('%.2f'%r3)
print('%.2f'%r4)