num = input("Enter a series of numbers separated by commas: ")
nums = num.split(',')
x1 = int(nums[0])
x2 = int(nums[1])
x3 = int(nums[2])
x4 = int(nums[3])
x5 = int(nums[4])
max = int(max(nums))
print(f"{x1} is the maximum value: ",x1 is max)
print(f"{x2} is the maximum value: ",x2 is max)
print(f"{x3} is the maximum value: ",x3 is max)
print(f"{x4} is the maximum value: ",x4 is max)
print(f"{x5} is the maximum value: ",x5 is max)