nums_text = ('Enter a series of numbers separated by commas:')
 num_s = num_stext.split(",")
 nums[0] = int(num[0])
 nums[1] = int(num[1])
 nums[2] = int(num[2])
 nums[3] = int(num[3])
 nums[4] = int(num[4])


 x_min = min(nums)
 x_max = min(nums)
 print(x_min,x_min)
 r0 = (nums[0] - x_min)
 r1 = (nums[1] - x_min)
 r2 = (nums[2] - x_min)
 r3 = (nums[3] - x_min)
 r4 = (nums[4] - x_min)
 print('Normalized values:')
 print("%.2f" % r0)
 print("%.2f" % r1)
 print("%.2f" % r2)
 print("%.2f" % r3)
 print("%.2f" % r4)
 #result = [0, 10, 20, 40]