x = input('Enter a series of numbers separated by commas: ')
x = x.split(",")
x[0] = int(x[0])
x[1] = int(x[1])
x[2] = int(x[2])
x[3] = int(x[3])
x[4] = int(x[4])
x_min = min(x)
x_max = max(x)
r0 = (x[0]-x_min) / (x_max-x_min)
r1 = (x[1]-x_min) / (x_max-x_min)
r2 = (x[2]-x_min) / (x_max-x_min)
r3 = (x[3]-x_min) / (x_max-x_min)
r4 = (x[4]-x_min) / (x_max-x_min)
print("Normalized values: %.2f" %(r0))
print("%.2f" %(r1))
print("%.2f" %(r2))
print("%.2f" %(r3))
print("%.2f" %(r4))