num = input("Enter a series of numbers separated by commas: ")
num = num.split(',')
x1 = int(num[0])
x2 = int(num[1])
x3 = int(num[2])
x4 = int(num[3])
x5 = int(num[4])
max = max(num)
print(f"{x1} is the maximum value: ",x1 is max)
print(f"{x2} is the maximum value: ",x2 is max)
print(f"{x3} is the maximum value: ",x3 is max)
print(f"{x4} is the maximum value: ",x4 is max)
print(f"{x5} is the maximum value: ",x5 is max)