num  = input("Enter a series of numbers separated by commas: ")
nums = num.split(',')
num1 = int(nums[0])
num2 = int(nums[1])
num3 = int(nums[2])
num4 = int(nums[3])
num5 = int(nums[4])
max = int(max(nums))
min = int(min(nums))
x1 = (num1-min) / (max-min)
x2 = (num2-min) / (max-min)
x3 = (num3-min) / (max-min)
x4 = (num4-min) / (max-min)
x5 = (num5-min) / (max-min)

print("Normalized values: %.2f " % x1, "%.2f " % x2, "%.2f " % x3, "%.2f " % x4, "%.2f " % x5)