nums = input('Enter a series of numbers separated by commas: ')
nums = nums.split(',')
num0 = int(nums[0])
num1 = int(nums[1])
num2 = int(nums[2]) 
num3 = int(nums[3]) 
num4 = int(nums[4]) 
num_max = max(nums)
print(num0 ,'is the maximum value:',num0 is num_max)
print(num1 ,'is the maximum value:',num1 is num_max)
print(num2 ,'is the maximum value:',num2 is num_max)
print(num3 ,'is the maximum value:',num3 is num_max)
print(num4 ,'is the maximum value:',num4 is num_max)