num = input('Enter a series of numbers separated by commas: ')
num = num.split(',')
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2]) 
num[3] = int(num[3]) 
num[4] = int(num[4]) 
num_max = max(num)
print(num[0] ,'is the maximum value:',num[0] is num_max)
print(num[1] ,'is the maximum value:',num[1] is num_max)
print(num[2] ,'is the maximum value:',num[2] is num_max)
print(num[3] ,'is the maximum value:',num[3] is num_max)
print(num[4] ,'is the maximum value:',num[4] is num_max)