num_e = input("Enter a series of numbers separated by commas:")
num = num_e.split(',')
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

x_max = max(num)
print("10 is the maximum value:" num[0] in num)
print("1 is the maximum value:" num[1] in num)
print("5 is the maximum value:" num[2] in num)
print("1 is the maximum value:" num[3] in num)
print("7 is the maximum value:" num[4] in num)