user = input("Enter a series of numbers separated by commas: ")
sp = user.split(",")
sp[0] = int(sp[0])
sp[1] = int(sp[1])
sp[2] = int(sp[2])
sp[3] = int(sp[3])
sp[4] = int(sp[4])
nummax = max(sp)
nummin = min(sp)

print(nummax)
print(nummin)

print(sp)
print(f"{sp[0]} is the maximum value: {sp[0] > nummax}")
print(f"{sp[1]} is the maximum value: {sp[1] > nummax}")
print(f"{sp[2]} is the maximum value: {sp[2] > nummax}")
print(f"{sp[3]} is the maximum value: {sp[3] > nummax}")
print(f"{sp[4]} is the maximum value: {sp[4] > nummax}")