num_text=input('Enter a series of numbers separated by commas : ')
num =num_text.split(",")
num[0]=int(num[0])
num[1]=int(num[1])
num[2]=int(num[2])
num[3]=int(num[3])
num[4]=int(num[4])
_min=min(num)
_max=max(num)
lower=_max-_min
print('Normalized values:')
print(f"{num[0]-_min/(_max-_min):2f}")
print(f"{num[1]-_min/(_max-_min):2f}")
print(f"{num[2]-_min/(_max-_min):2f}")
print(f"{num[3]-_min/(_max-_min):2f}")
print(f"{num[4]-_min/(_max-_min):2f}")