Num5 = input('Enter a series of numbers separated by commas: ')

Num5 = Num5.split(",")
Num5[0] = int(Num5[0])
Num5[1] = int(Num5[1])
Num5[2] = int(Num5[2])
Num5[3] = int(Num5[3])
Num5[4] = int(Num5[4])

print('Normalized values:')
minx = min(Num5)
maxx = max(Num5)
r1 = (Num5[0] - minx)/(maxx-minx)
r2 = (Num5[1] - minx)/(maxx-minx)
r3 = (Num5[2] - minx)/(maxx-minx)
r4 = (Num5[3] - minx)/(maxx-minx)
r5 = (Num5[4] - minx)/(maxx-minx)

print(r1)
print(r2)
print(r3)
print(r4)
print(r5)