nums_text = input("Enter a series of numbers separated by commas: ")
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
print(nums)
_min = min(nums)
_max = max(nums)
print("Normalized values:")
print(f"{(nums[0]-_min)  /(_max-_min):.2f}")
print(f"{(nums[1]-_min)  /(_max-_min):.2f}")
print(f"{(nums[2]-_min)  /(_max-_min):.2f}")
print(f"{(nums[3]-_min)  /(_max-_min):.2f}")
print(f"{(nums[4]-_min)  /(_max-_min):.2f}")