x_text = input("Enter a series of numbers separated by commas:")
x = x_text.split(",")
x[0] = int(x[0])
x[1] = int(x[1])
x[2] = int(x[2])
x[3] = int(x[3])
x[4] = int(x[4])
min_x = min(x)
max_x = max(x)
r1 = (x[0]-min_x)/(max_x-min_x)
r2 = (x[1]-min_x)/(max_x-min_x)
r3 = (x[2]-min_x)/(max_x-min_x)
r4 = (x[3]-min_x)/(max_x-min_x)
r5 = (x[4]-min_x)/(max_x-min_x)

print("Normalized values: %.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)
print("%.2f" % r5)