x = input("Enter a series of numbers separated by commas:")
x = x.split(',')
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
print(x[0],"is the maximum value:",x[0] is max(x))
print(x[1],"is the maximum value:",x[1] is max(x))
print(x[2],"is the maximum value:",x[3] is max(x))
print(x[3],"is the maximum value:",x[3] is max(x))
print(x[4],"is the maximum value:",x[4] is max(x))