x = input("Enter a series of numbers separated by commas: ")
nums = x.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])

y1 = nums[0]>=max(nums)
y2 = nums[1]>=max(nums)
y3 = nums[2]>=max(nums)
y4 = nums[3]>=max(nums)
y5 = nums[4]>=max(nums)

print(nums[0],'is the maximum value: ', y1 )
print(nums[1],'is the maximum value: ', y2)
print(nums[2],'is the maximum value: ', y3)
print(nums[3],'is the maximum value: ', y4)
print(nums[4],'is the maximum value: ', y5)