Blablabla = ("Enter a series of numbers separated by commas:")
Off = Blablabla.split(",")
O1 = int(Off[0])
O2 = int(Off[1])
O3 = int(Off[2])
O4 = int(Off[3])
O5 = int(Off[4])

IO = max(Off)
print(O1, "is the maximum value:", O1 == IO)
print(O2, "is the maximum value:", O1 == IO)
print(O3, "is the maximum value:", O1 == IO)
print(O4, "is the maximum value:", O1 == IO)
print(O5, "is the maximum value:", O1 == IO)