Blablabla = input("Enter a series of numbers separated by commas:")
Off = Blablabla.split(",")
Off[0] = int(Off[0])
Off[1] = int(Off[1])
Off[2] = int(Off[2])
Off[3] = int(Off[3])
Off[4] = int(Off[4])
Max = max(Off)

print(Off[0]," is the maximum value: ",Off[0] == Max)
print(Off[1]," is the maximum value: ",Off[0] == Max)
print(Off[2]," is the maximum value: ",Off[0] == Max)
print(Off[3]," is the maximum value: ",Off[0] == Max)
print(Off[4]," is the maximum value: ",Off[0] == Max)