x = input("Enter a series of numbers separated by commas: ")
x = x.split(",")
x[0] = int(x[0])
x[1] = int(x[1])
x[2] = int(x[2])
x[3] = int(x[3])
x[4] = int(x[4])
print("Normalized values")
print(f"{(x[0]-min(x))/(max(x)):.2f)")
print(f"{(x[1]-min(x))/(max(x)):.2f)")
print(f"{(x[2]-min(x))/(max(x)):.2f)")
print(f"{(x[3]-min(x))/(max(x)):.2f)")
print(f"{(x[4]-min(x))/(max(x)):.2f)")