nums_text = input("Enter a series of numbers separated by commas:")
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
min_x = min(nums)
max_x = max(nums)
x0 = (nums[0] - min_x)/(max_x - min_x)
x1 = (nums[1] - min_x)/(max_x - min_x)
x2 = (nums[2] - min_x)/(max_x - min_x)
x3 = (nums[3] - min_x)/(max_x - min_x)
x4 = (nums[4] - min_x)/(max_x - min_x)
print("%.2f" %x0)
print("%.2f" %x1)
print("%.2f" %x2)
print("%.2f" %x3)
print("%.2f" %x4)