nums_text = input("Enter a series of numbers separated by commas:")
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
max_x =max[nums]
print(max_x,'is the maximum value',max_x in nums)
print(max_x,'is the maximum value',max_x in nums)
print(max_x,'is the maximum value',max_x in nums)
print(max_x,'is the maximum value',max_x in nums)