nums_text=input('Enter a series of numbers separated by commas: ')
nums =nums_text.split(",")
nums[0]=int(nums[0])
nums[1]=int(nums[1])
nums[2]=int(nums[2])
nums[3]=int(nums[3])
nums[4]=int(nums[4])

_max=max(nums)
print(f"{num[0]}is the maximum value:{num[0]is _max}")
print(f"{num[1]}is the maximum value:{num[1]is _max}")
print(f"{num[2]}is the maximum value:{num[2]is _max}")
print(f"{num[3]}is the maximum value:{num[3]is _max}")
print(f"{num[4]}is the maximum value:{num[4]is _max}")