nums_text = input("Enter a series of numbers separated by commas:\n")
nums = nums_text.split(',')
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])

_Min = min(nums)
_Max = max(nums)
r0 = (nums[0]-_Min)/(_Max-_Min)
r1 = (nums[1]-_Min)/(_Max-_Min)
r2 = (nums[2]-_Min)/(_Max-_Min)
r3 = (nums[3]-_Min)/(_Max-_Min)
r4 = (nums[4]-_Min)/(_Max-_Min)
print("Normalized values:",end='\n')
print("%.2f" % r0,"%.2f" % r1,"%.2f" % r2,"%.2f" % r3,"%.2f" % r4,sep="\n")

print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)