nums = nums_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])
min_x = min(nums)
max_x = max(nums)
#min_x = min(nums)

r0 = (nums[0] - _min / max_x - min_x)
r1 = (nums[1] - _min / max_x - min_x)
r2 = (nums[2] - _min / max_x - min_x)
r3 = (nums[3] - _min / max_x - min_x)
r4 = (nums[4] - _min / max_x - min_x)
print("Normalized values")
print("%.2f" % r0)
print("%.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)