nums_text= input("Enter a series of numbers separated by commas: ")
nums = nums_text.split(",")
nums[0] = int(num[0])
nums[1] = int(num[1])
nums[2] = int(num[2])
nums[3] = int(num[3])
nums[4] = int(num[4])

x_min = min(nums)
x_max = max(nums)

r0 = (nums[0] - x_min)/(x_max-x_min)
r1 = (nums[1] - x_min)/(x_max-x_min)
r2 = (nums[2] - x_min)/(x_max-x_min)
r3 = (nums[3] - x_min)/(x_max-x_min)
r4 = (nums[4] - x_min)/(x_max-x_min)

print("Normalized value:")
print("%.2f" % r0)
print("%.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)