nums_text = ("Enter a series of numbers separated by commas: ")
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
min_x = min(nums)
max_x = max(nums)

r0 = (nums[0] - _min)/(max_x - min_x)
r1 = (nums[1] - _min)/(max_x - min_x)
r2 = (nums[2] - _min)/(max_x - min_x)
r3 = (nums[3] - _min)/(max_x - min_x)
r4 = (nums[4] - _min)/(max_x - min_x)
print(f"Normalized values: \n{r0:.2f}\n{r1:.2f}\n{r2:.2f}\n{r3:.2f}\n{r4:.2f}")