number = input("Enter a series of numbers separated by commas: ")
nums = number.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
maximum = max(nums)
print(f"{nums[0]} is the maxmum value:", nums[0] is maximum)
print(f"{nums[1]} is the maxmum value:", nums[1] is maximum)
print(f"{nums[2]} is the maxmum value:", nums[2] is maximum)
print(f"{nums[3]} is the maxmum value:", nums[3] is maximum)
print(f"{nums[4]} is the maxmum value:", nums[4] is maximum)