x1 = input("Enter the x-coordinate of point 1:")
y1 = input("Enter the y-coordinate of point 1:")
x2 = input("Enter the x-coordinate of point 2:")
y2 = input("Enter the y-coordinate of point 2:")
x1 = int(x1)
x2 = int(x2)
y1 = int(y1)
y2 = int(y2)
import math
slope (x2-x1)**2 + (y2-y1)**2)
slope =math.sqrt(slope)
print("The distance between the two points is: %2f" %slope)