x_scaled = int(input("Enter a series of numbers separated by commas: "))
nums = nums_text.split(",")
_min = min(x_scaled)
_max = max(x_scaled)
x = x-min(x)%max(x)-min(x)
print =("Normalized values:x ")