nums input(Enter a series of numbers separated by commas")

num = nums. split(",")
num[0]= int (num[0])
num[1]= int (num[1])
num[2]= int (num[2])
num[3]= int (num[3])
num[4]= int (num[4])

_min = min (num)
_max = max (num)
ro = (num[0]-_min)/(_max-_min)
r1 = (num[1]-min)/(_max-_min)
r2 = (num[2]-min)/(_max-_min)
r3 = (num[31-min)/(_max- min)
r4 = (num[4]-_min)/(_max-_min)
             
print(f"Normalized values:")
print ("%.2f"% r0)
print ("%.2f"% r1)
print ("%.2f"% r2)
print ("%.2f"% r3)
print ("%.2f"% r4)