x_scaled = int(input("Enter a series of numbers separated by commas: "))
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
print =("Normalized values: ")