nums_tex= input('Enter a series of numbers separated by commas:')
nums = nums_tex.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])

hee =  max(nums)
r0 = (nums[0] == hee)
r1 = (nums[1] == hee)
r2 = (nums[2] == hee)
r3 = (nums[3] == hee)
r4 = (nums[4] == hee)

print(f'{nums[0]}is the maximum value:{r0}')
print(f'{nums[1]}is the maximum value:{r1}')
print(f'{nums[2]}is the maximum value:{r2}')
print(f'{nums[3]}is the maximum value:{r3}')
print(f'{nums[4]}is the maximum value:{r4}')