jek = input("Enter a series of numbers separated by commas")
kk = jek.split(",")
kk[0]=int(kk[0])
kk[1]=int(kk[1])
kk[2]=int(kk[2])
kk[3]=int(kk[3])
kk[4]=int(kk[4])

mi = min(kk)
mx = max(kk)

print(kk[0],"is the maximum value:",kk[0] is mx)
print(kk[1],"is the maximum value:",kk[1] is mx)
print(kk[2],"is the maximum value:",kk[2] is mx)
print(kk[3],"is the maximum value:",kk[3] is mx)
print(kk[4],"is the maximum value:",kk[4] is mx)