A = input("Enter a series of numbers separated by commas:")
B = A.split(",")
B[0] = int(B[0])
B[1] = int(B[1])
B[2] = int(B[2])
B[3] = int(B[3])
B[4] = int(B[4])

ma = max(B)
print("B[0]is the maximum value:",B[0] is ma)
print("B[0]is the maximum value:",B[1] is ma)
print("B[0]is the maximum value:",B[2] is ma)
print("B[0]is the maximum value:",B[3] is ma)
print("B[0]is the maximum value:",B[4] is ma)