x = input("Enter a series of numbers separated by commas:")
nums = x.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
_min = min(nums)
_max = max(nums)
print (nums)
print (_min)
print (_max)