jek = input("Enter a series of numbers separated by commas:")
kk = jek.split(",")
kk[0]=int(kk[0])
kk[1]=int(kk[1])
kk[2]=int(kk[2])
kk[3]=int(kk[3])

mi = min(kk)
mx = max(kk)
gg = [(kk[0]-mi)/(mx-mi),(kk[1]-mi)/(mx-mi),(kk[2]-mi)/(mx-mi),(kk[3]-mi)/(mx-mi)]
print("Normalized values:")
print((kk[0]-mi)/(mx-mi))
print((kk[1]-mi)/(mx-mi))
print((kk[2]-mi)/(mx-mi))
print((kk[3]-mi)/(mx-mi))