x = input("Enter a series of numbers separated by commas: ")
num = x.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

_min = min(num)
_max = max(num)
#print(_max,_min)
x_scaled = (-_min)/(_max-_min)
print("Normalized values: %.2f" % x_scaled)