x = input("Enter a series of numbers separated by commas:")
nums = x.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
_min = min(nums)
_max = max(nums)
print (nums)




x0 = ((nums[0])-(_min))/((_max )-(_min))
x1 = ((nums[1])-(_min))/((_max )-(_min))
x2 = ((nums[2])-(_min))/((_max )-(_min))
x3 = ((nums[3])-(_min))/((_max )-(_min))
x4 = ((nums[4])-(_min))/((_max )-(_min))
print ("Normalized values:  ")
print("%.2f" % x0  )
print("%.2f" % x1  )
print("%.2f" % x2  )
print("%.2f" % x3  )
print("%.2f" % x4  )