x = (input("Enter a series of numbers separated by commas:"))
a = x.split(",")
a[0] = int(a[0])
a[1] = int(a[1])
a[2] = int(a[2])
a[3] = int(a[3])
a[4] = int(a[4])
max_n = (max(a))
print(f"10 is the maximum value:{a[0] == max_n}")
print(f"1 is the maximum value:{a[1] == max_n}")
print(f"5 is the maximum value:{a[2] == max_n}")
print(f"1 is the maximum value:{a[3] == max_n}")
print(f"7 is the maximum value:{a[4] == max_n}")