A = (input("Enter a series of numbers separated by commas:"))
B = A.split(",")
B[0] = int(B[0])
B[1] = int(B[1])
B[2] = int(B[2])
B[3] = int(B[3])
B[4] = int(B[4])

mi = min(B)
ma = max(B)
r0 = (B[0]-mi)/(ma-mi)
r1 = (B[1]-mi)/(ma-mi)
r2 = (B[2]-mi)/(ma-mi)
r3 = (B[3]-mi)/(ma-mi)
r4 = (B[4]-mi)/(ma-mi)

print(f''Normalized value: \n{r0:.2f}\n{r1:.2f}\n{r2:.2f}\n{r3:.2f}\n{r4:.2f}"")