nums_text = input(”Enter a series of numbers separated by commas:“)
nums = nums_text.split(”,“)
nums[0] =int(nums[0])
nums[1] =int(nums[1])
nums[2] =int(nums[2])
nums[3] =int(nums[3])
nums[4] =int(nums[4])
x0 = int(nums[0])
x1 = int(nums[1])
x2 = int(nums[2])
x3 = int(nums[3])
x4 = int(nums[4])
min_x = min(nums)
max_x = max(nums)
print(x0, ”is the maximum value:“, x0 is max_x)
print(x1, ”is the maximum value:“, x1 is max_x)
print(x2, ”is the maximum value:“, x2 is max_x)
print(x3, ”is the maximum value:“, x3 is max_x)
print(x4, ”is the maximum value:“, x4 is max_x)