x,y = input().split(',')
x = int(x)
y= int(y)

print(f"{x}+{y}is{x+y}")
print(f"{x}-{y}is{x-y}")
print(f"{x}*{y}is{x*y}")
print(f"{x}/{y}is{x/y}")
print(f"{x}//{y}is{x//y}")
print(f"{x}%{y}is{x%y}")
print(f"{x}**{y}is{x**y}")