a,b = input(""),split(',')
print(a,'+',b,'=',int(a)+int(b))
print(a,'-',b,'=',int(a)-int(b))
print(a,'*',b,'=',int(a)*int(b))
print(a,'/',b,'=',int(a)/int(b))
print(a,'//',b,'=',int(a)//int(b))
print(a,'%',b,'=',int(a)%int(b))
print(a,'**',b,'=',int(a)**int(b))