a,b = input().split(',')
a=float(a)
b=float(b)

print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"/",b,"=",a/b)
print(a,"//",b,"=",a//b)
print(a,"%",b,"=",a%b)
print(a,"**",b,"=",a**b)