x=input.split(" , ")
print('Addition: ', x)
print('Subtraction: ', x)
print('Multiplication: ',x)
print('Division: ',x)
print('Division without the remainder: ',x)
print('Modulus: ',x)
print('Exponential: ',x)