x=input().split(" , ")
print('Addition: ')
print('Subtraction: ')
print('Multiplication: ')
print('Division: ')
print('Division without the remainder: ')
print('Modulus: ')
print('Exponential: ')
print("sum is ",int(x[0])'Addition'int(x[1]))