number = input()
print(number[0] + number[1])
print(number[0] - number[1])
print(number[0] * number[1])
print(number[0] / number[1])
print(number[0] // number[1])
print(number[0] % number[1])
print(number[0] ** number[1])