numbers = input()
num1, num2 = numbers.split(",")
print(int(num1)+int(num2))
print(int(num1) - int(num2))
print(int(num1) * int(num2))  
print(int(num1) / int(num2))                       
print(int(num1) // int(num2))
print(int(num1) % int(num2)) 
print(int(num1) ** int(num2))