x,y = input().split(',')
print(int(x),'+',int(y),"=",int(x)+int(y))
print(int(x),'-',int(y),"=",int(x)-int(y))
print(int(x),'*',int(y),"=",int(x)*int(y))
print(int(x),'/',int(y),"=",int(x)/int(y),(type(int(x)/int(y))))
print(int(x),'//',int(y),"=",int(x)//nt(y))
print(int(x),'%',int(y),"=",int(x)%int(y))
print(int(x),'**',int(y),"=",int(x)**int(y))