number=input().split0(',')
num1=[0]
num2=[1]
num1=int(num1)
num2=int(num2)
print(int(num1)+int(num2))
print(int(num1)-int(num2))
print(int(num1)*int(num2))
print(int(num1)/int(num2))
print(int(num1)//int(num2))
print(int(num1)%int(num2))
print(int(num1)**int(num2))