result = input()
num1, num2 = numbers.split(",")
result = int(num1) + int(num2)
result = int(num1) - int(num2
result = int(num1) * int(num2)  
result = int(num1) / int(num2)                        
result = int(num1) // int(num2)
result = int(num1) % int(num2) 
result = int(num1) ** int(num2)     
print(result)