innum, num = input().split(','), int(innum)
print(num[0],'+',num[1],'=',num[0] + num[1])
print(num[0],'-',num[1],'=',num[0] - num[1])
print(num[0],'*',num[1],'=',num[0] * num[1])
print(num[0],'/',num[1],'=',num[0] / num[1])
print(num[0],'//',num[1],'=',num[0] // num[1])
print(num[0],'%',num[1],'=',num[0] % num[1])
print(num[0],'**',num[1],'=',num[0] ** num[1])