print = input()split(',')
x = input(a)
y = input(b)
print = (f'a+b = [a+b]')
print = (f'a-b = [a-b]')
print = (f'a*b = [a*b]')
print = (f'a/b = [a/b]')
print = (f'a//b = [a//b]')
print = (f'a%b = [a%b]')
print = (f'a**b = [a**b]')