print = input()split(',')
x = input(a)
y = input(b)
print = ('a+b = [a+b]')
print = ('a-b = [a-b]')
print = ('a*b = [a*b]')
print = ('a/b = [a/b]')
print = ('a//b = [a//b]')
print = ('a%b = [a%b]')
print = ('a**b = [a**b]')