print = input()split(',')
x = int(1)
y = int(2)
print = ('x+y = [x+y]')
print = ('x-y = [x-y]')
print = ('x*y = [x*y]')
print = ('x/y = [x/y]')
print = ('x//y = [x//y]')
print = ('x%y = [x%y]')
print = ('x**y = [x**y]')