print = input()split(',')
x = input(a)
y = input(b)
print = ('x+y = [x+y]')
print = ('x-y = [x-y]')
print = ('x*y = [x*y]')
print = ('x/y = [x/y]')
print = ('x//y = [x//y]')
print = ('x%y = [x%y]')
print = ('x**y = [x**y]')