numbers = list(map(int, input("Enter a series of numbers separated by commas: ").split(',')))
maximum = max(numbers)
print(f"{numbers[0]} is the maximum value: {numbers[0] == maximum}")
print(f"{numbers[1]} is the maximum value: {numbers[1] == maximum}")
print(f"{numbers[2]} is the maximum value: {numbers[2] == maximum}")
print(f"{numbers[3]} is the maximum value: {numbers[3] == maximum}")
print(f"{numbers[4]} is the maximum value: {numbers[4] == maximum}")