i1 = input('Enter item 1 : ')
w1 = float(input('Enter weight 1 : '))
i2 = input('Enter item 2 : ')
w2 = float(input('Enter weight 2 : '))
i3 = input('Enter item 3 : ')
w3 = float(input('Enter weight 3 : '))
i4 = input('Enter item 3 : ')
w4 = float(input('Enter weight 4 : '))
total = w1 + w2 + w3 + w4

print(i1,'\t','\t','\t','\t','\t','\t',w1)
print(i2,'\t','\t','\t','\t','\t','\t',w2)
print(i3,'\t','\t','\t','\t','\t','\t',w3)
print(i4,'\t','\t','\t','\t','\t','\t',w4)
print('---------------------------')
print(f'toal\t\t\t\t\t\t{total:.2f}')