a=input("Enter item 1 : ")
b=input("Enter weight 1 :")
c=input("Enter item 2 :")
d=input("Enter weight 2 :")
e=input("Enter item 3 :")
f=input("Enter weight 3 :")
g=input("Enter item 4 :")
h=input("Enter weight 4 :")
kee=b+d+f+h
print(a           ,b           ,c           ,d           ,e           ,f           ,g           ,h)
print("---------------------------")
print('total')
print(kee)