item1 = input("item 1")
weight1 = float(input("weight 1 "))
item2 = input("item 2")
weight2 = float(input("weight 2 "))
item3 = input("item 3")
weight3 = float(input("weight 3 "))
item4 = input("item 4")
weight4 = float(input("weight 4 "))
print(item1,"           ","%.2f" %weight1)
print(item2,"           ","%.2f" %weight2)
print(item3,"           ","%.2f" %weight3)
print(item4,"           ","%.2f" %weight4)
print("---------------------------")
a = weight1+weight2+weight3+weight4
print(f"total           {a:.2f}")