x = str(input("Enter item 1 : "))
y = float(input("Enter weight 1 :"))
z = str(input("Enter item 2 : "))
s = float(input("Enter weight 2 :"))
d = str(input("Enter item 3 : "))
a = float(input("Enter weight 3 :"))
w = str(input("Enter item 4 : "))
e = float(input("Enter weight 4 :"))

print(x,"           "f'{y:.2f}')
print(z,"           "f'{s:.2f}')
print(d,"           "f'{a:.2f}')
print(w,"           "f'{e:.2f}')
n = y + s + a + e
print("total           ",n)