fruit1 = input("Enter item 1 :")
weight1 = float(input("Enter weight 1 :"))
fruit2 = input("Enter item 2 :")
weight2 = float(input("Enter weight 2:"))
fruit3 = input("Enter item 3 :")
weight3 = float(input("Enter weight 3 :"))
fruit4 = input("Enter item 4 :")
weight4 = float(input("Enter weight 4 :"))
total = weight1 + weight2 + weight3 + weight4
print(fruit1,weight1)
print(fruit2,weight2)
print(fruit3,weight3)
print(fruit4,weight4)
print("---------------------------")
print(f"total{total}")