iM = input("Enter item 1:")
weM = float(input("Enter weight 1:"))
iW = input("Enter item 2:")
weW = float(input("Enter weight 2:"))
ik = input("Enter item 3:")
wek = float(input("Enter weight 3:"))
il = input("Enter item 4:")
wel = float(input("Enter weight 4:"))
sp = "        "
print(iM,sp,"%.2f"%weM)
print(iW,sp,"%.2f"%weW)
print(ik,sp,"%.2f"%wek)
print(il,sp,"%.2f"%wel)
print("------------------")
print('total',sp,"%.2f"%(weM+weW+wek+wel))