n = input("Display multiplication table of?" )
num_int = int(n)
cal = num_int * 1
cal2 = num_int * 2
cal3 = num_int * 3
cal4 = num_int * 4
cal5 = num_int * 5
cal6 = num_int * 6
print(n,"x 1 =",cal)
print(n,"x 2 =",cal2)
print(n,"x 3 =",cal3)
print(n,"x 4 =",cal4)
print(n,"x 5 =",cal5)
print(n,"x 6 =",cal6)