n1 = input("Enter your name:")
n1=str(n1)
n2 = input("Enter your email:")
n2=str(n2)
lang = input("Enter your GPA:")
lang=float(lang)
a = [n1,n2,lang]
b = (n1,n2,lang)
c = {"name":n1,"email":n2,"GPA":lang}
print(a,b,c,sep="\n")