n = input()
n_ = n.split(",")
print(n_[0],"+",n_[1],'=', int(n_[0])+int(n_[1]),sep='')
print(n_[0],"-",n_[1],'=', int(n_[0])-int(n_[1]),sep='')
print(n_[0],"*",n_[1],'=', int(n_[0])*int(n_[1]),sep='')
print(n_[0],"/",n_[1],'=', int(n_[0])/int(n_[1]),sep='')
print(n_[0],"//",n_[1],'=', int(n_[0])//int(n_[1]),sep='')
print(n_[0],"%",n_[1],'=', int(n_[0])%int(n_[1]),sep='')
print(n_[0],"**",n_[1],'=', int(n_[0])**int(n_[1]),sep='')