A = input().split(',')
B = int(A[0])
C = int(A[1])
D = B + C
E = B - C
F = B * C
G = B / C
H = B // C
I = B % C
J = B ** C
print(B,"+",C,"=",D)
print(B,"-",C,"=",E)
print(B,"*",C,"=",F)
print(B,"/",C,"=",G)
print(B,"//",C,"=",H)
print(B,"%",C,"=",I)
print(B,"**",C,"=",J)