data = input()
num1 , num2 = data.split(',')
num1 = int(num1)
num2 = int(num2)
a = num1 + num2
b = num1 - num2
c = num1 * num2
d = num1 / num2
e = num1 // num2
f = num1 % num2
g = num1 ** num2
print(num1,'+',num2 ,'=', a)
print(num1,'-',num2 ,'=', b)
print(num1,'*',num2 ,'=', c)
print(num1,'/',num2 ,'=', d)
print(num1,'//',num2 ,'=',e)
print(num1,'%',num2 ,'=', f)
print(num1,'**',num2 ,'=', g)