x=input()
y=x.split(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')
x=input()
y=x.split(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')
x=input()
y=x.split(',')
print(f'First number is:{y[0]}')
print(f'Second number is:{y[1]}')