number = input()
x = number.split(",")
print(x[0],"+",x[1],"=",int(x[0])+int(x[1]),sep="")
print(x[0],"-",x[1],"=",int(x[0])-int(x[1]),sep="")
print(x[0],"*",x[1],"=",int(x[0])*int(x[1]),sep="")
print(x[0],"/",x[1],"=",int(x[0])/int(x[1]),sep="")
print(x[0],"//",x[1],"=",int(x[0])//int(x[1]),sep="")
print(x[0],"%",x[1],"=",int(x[0])%int(x[1]),sep="")
print(x[0],"**",x[1],"=",int(x[0])**int(x[1]),sep="")