x = input("Enter a series of numbers separated by commas: ").split(",")
x[0] = int(x[0])
x[1] = int(x[1])
x[2] = int(x[2])
x[3] = int(x[3])
x[4] = int(x[4])
x_min = min(x)
x_max = max(x)
x1 =(x[0]-x_min)/(x_max-x_min)
x2 =(x[1]-x_min)/(x_max-x_min)
x3 =(x[2]-x_min)/(x_max-x_min)
x4 =(x[3]-x_min)/(x_max-x_min)
x5 = (x[4]-x_min)/(x_max-x_min)
print(f"Normalized values:")
print (f"{x1:.2f}\n{x2:.2f}\n{x3:.2f}\n{x4:.2f}\n{x5:.2f}")