nums1 = input("Enter a series of numbers separated by commas: ")
nums = nums1.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
x_min = min(nums)
x_max = max(nums)
p0 = (nums[0] - x_min) / (x_max - x_min)
p1 = (nums[1] - x_min) / (x_max - x_min)
p2 = (nums[2] - x_min) / (x_max - x_min)
p3 = (nums[3] - x_min) / (x_max - x_min)
p4 = (nums[4] - x_min) / (x_max - x_min)
print("Normalized values: ")
print("%.2f"%p0) 
print("%.2f"%p1) 
print("%.2f"%p2) 
print("%.2f"%p3) 
print("%.2f"%p4)