x = input("Enter a series of numbers separated by commas: ").split(',')
x_list = [int(x[0]),int(x[1]),int(x[2]),int(x[3]),int(x[4]),]
xmin = min(x_list)
xmax = max(x_list)
x1 = (x_list[0]-xmin)/(xmax-xmin)
x2 = (x_list[1]-xmin)/(xmax-xmin)
x3 = (x_list[2]-xmin)/(xmax-xmin)
x4 = (x_list[3]-xmin)/(xmax-xmin)
x5 = (x_list[4]-xmin)/(xmax-xmin)
print("Normalized values: ")
print("%.2f"%x1)
print("%.2f"%x2)
print("%.2f"%x3)
print("%.2f"%x4)
print("%.2f"%x5)