nums_text = input('Enter a series of numbers separated by commas: ')
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
x_min = min(nums)
x_max = max(nums)
x_scaled0 = (nums[0]-x_min)/(x_max-x_min)
x_scaled1 = (nums[1]-x_min)/(x_max-x_min)
x_scaled2 = (nums[2]-x_min)/(x_max-x_min)
x_scaled3 = (nums[3]-x_min)/(x_max-x_min)
x_scaled4 = (nums[4]-x_min)/(x_max-x_min)
print('Normalized values:')
print("%.2f" % x_scaled0)
print("%.2f" % x_scaled1)
print("%.2f" % x_scaled2)
print("%.2f" % x_scaled3)
print("%.2f" % x_scaled4)