num = input("Enter a series of numbers separated by commas: ")
nums = num.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
nummin = min(nums)
nummax = max(nums)

a1 = (nums[0] - nummin)/(nummax - nummin)
a2 = (nums[1] - nummin)/(nummax - nummin)
a3 = (nums[2] - nummin)/(nummax - nummin)
a4 = (nums[3] - nummin)/(nummax - nummin)
a5 = (nums[4] - nummin)/(nummax - nummin)
print(f"Normalized values:\n{a1 :.2f}\n{a2 :.2f}\n{a3 :.2f}\n{a4 :.2f}\n{a5 :.2f}")