num_text = input("Enter a series of numbers separated by commas: ")
num = num_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])
x_min =  min(num)
x_max = max(num)
r0 = (num[0] - x_min)/(x_max-x_min)
r1 = (num[1] - x_min)/(x_max-x_min)
r2 = (num[2] - x_min)/(x_max-x_min)
r3 = (num[3] - x_min)/(x_max-x_min)
r4 = (num[4] - x_min)/(x_max-x_min)
print('Normalized values:')
print("%.2f"%r0)
print("%.2f"%r1)
print("%.2f"%r2)
print("%.2f"%r3)
print("%.2f"%r4)