user = input("Enter a series of numbers separated by commas: ")
sp = user.split(",")
sp[0] = int(sp[0])
sp[1] = int(sp[1])
sp[2] = int(sp[2])
sp[3] = int(sp[3])
sp[4] = int(sp[4])
nummax = max(sp)
nummin = min(sp)
a0 = (sp[0] - nummin) / (nummax - nummin)
a1 = (sp[1] - nummin) / (nummax - nummin)
a2 = (sp[2] - nummin) / (nummax - nummin)
a3 = (sp[3] - nummin) / (nummax - nummin)
a4 = (sp[4] - nummin) / (nummax - nummin)

print(f"Normalized values: \n{a0:.2f}\n{a1:.2f}\n{a2:.2f}\n{a3:.2f}\n{a4:.2f}")