x = input("Enter a series of numbers separated by commas:").split(',')
x_list =[int(x[0]),int(x[1]),int(x[2]),int(x[3]),int(x[4])]
x_min = min(x_list)
x_max = max(x_list)
x1 = (x_list[0]-x_min)/(x_max-x_min)
x2 = (x_list[1]-x_min)/(x_max-x_min)
x3 = (x_list[2]-x_min)/(x_max-x_min)
x4 = (x_list[3]-x_min)/(x_max-x_min)
x5 = (x_list[4]-x_min)/(x_max-x_min)
print("Normalized values:")
print("%.2f" %x1)
print("%.2f" %x2)
print("%.2f" %x3)
print("%.2f" %x4)
print("%.2f" %x5)