code= {'Dog': 0,'Cat' : 1 ,'Fish' : 2}
num_dict = {'Dog': [1, 0, 0], 'Cat' : [0, 1, 0] , 'Fish' : [0, 0, 1]}
pet = input('Enter your pets: ')
hex_str = (pet)
hex_num = hex_str.split(",")
print ("Code of your pets: ",end = ' ')
print(code[hex_num[0]] , code[hex_num[1]] , code[hex_num[2]],code[hex_num[3]] , code[hex_num[4]],sep=',')
print ("One-hot vectors:",end = '\n')
print(num_dict[hex_num[0]] , num_dict[hex_num[1]] , num_dict[hex_num[2]], num_dict[hex_num[3]],num_dict[hex_num[4]],sep='\n')