nums = input('Enter a series of numbers separated by commas: ')
sp = nums.split(",")
sp[0] = int(sp[0])
sp[1] = int(sp[1])
sp[2] = int(sp[2])
sp[3] = int(sp[3])
sp[4] = int(sp[4])
x_min = min(sp)
x_max = max(sp)
print(f'Normalized values: \n{(sp[0] - x_min)/(x_max - x_min):.2f} \n{(sp[1] - x_min)/(x_max - x_min):.2f} \n{(sp[2] - x_min)/(x_max - x_min):.2f} \n{(sp[3] - x_min)/(x_max - x_min):.2f} \n{(sp[4] - x_min)/(x_max - x_min):.2f}')