numx = input('Enter a series of numbers separated by commas: ')
num = numx.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])
xmax = max(num)
xmin = min(num)
r0 =(num[0]-xmin)/(xmax-xmin)
r1 =(num[1]-xmin)/(xmax-xmin)
r2 =(num[2]-xmin)/(xmax-xmin)
r3 =(num[3]-xmin)/(xmax-xmin)
r4 =(num[4]-xmin)/(xmax-xmin)
print("Normalized values:")
print("%.2f" % r0)
print("%.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)