nums = input('Enter a series of numbers separated by commas: ')
sp = nums.split(',')

sp[0] = int(sp[0])
sp[1] = int(sp[1])
sp[2] = int(sp[2])
sp[3] = int(sp[3])
sp[4] = int(sp[4])
x_min = min(sp)
x_max = max(sp)

print (f'{sp[0]} is the maximum value: {sp[0]>=x_max}')
print (f'{sp[1]} is the maximum value: {sp[1]>=x_max}')
print (f'{sp[2]} is the maximum value: {sp[2]>=x_max}')
print (f'{sp[3]} is the maximum value: {sp[3]>=x_max}')
print (f'{sp[4]} is the maximum value: {sp[4]>=x_max}')