num_text = str(input('Enter a series of numbers separated by commas: '))
num = num_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

r0 = ((num[0]-min(num))/(max(num)-min(num)))
r1 = ((num[1]-min(num))/(max(num)-min(num)))
r2 = ((num[2]-min(num))/(max(num)-min(num)))
r3 = ((num[3]-min(num))/(max(num)-min(num)))
r4 = ((num[4]-min(num))/(max(num)-min(num)))

print('Normalized values:')
print('%.2f' %r0)
print('%.2f' %r1)
print('%.2f' %r2)
print('%.2f' %r3)
print('%.2f' %r4)