a = input("Enter a series of numbers separated by commas:")
b = a.split(",")
b[0] = int(b[0])
b[1] = int(b[1])
b[2] = int(b[2])
b[3] = int(b[3])
b[4] = int(b[4])
max_b = max(b)
print(b[0],"is the maximum value:",b[0] == max_b)
print(b[1],"is the maximum value:",b[1] == max_b)
print(b[2],"is the maximum value:",b[2] == max_b)
print(b[3],"is the maximum value:",b[3] == max_b)
print(b[4],"is the maximum value:",b[4] == max_b)