mums_text = input('Enter a series of numbers separated by commas:')
num = mums_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

min_x = min(num)
max_x = max(num)

r0 = (num[0]-min_x)/(max_x-min_x)
r1 = (num[1]-min_x)/(max_x-min_x)
r2 = (num[2]-min_x)/(max_x-min_x)
r3 = (num[3]-min_x)/(max_x-min_x)
r4 = (num[4]-min_x)/(max_x-min_x)
print('Normalized values:')
print("%.2f" % r0)
print("%.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)