mums_text = input("Enter a series of numbers separated by commas:")
num = mums_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

max_x = max(num)

print(num[0],"is the maximum value:",num[0] is max_x)
print(num[1],"is the maximum value:",num[1] is max_x)
print(num[2],"is the maximum value:",num[2] is max_x)
print(num[3],"is the maximum value:",num[3] is max_x)
print(num[4],"is the maximum value:",num[4] is max_x)