x = (input("Enter a series of numbers separated by commas:"))
o = x.split(",")
a = min(o)
b = max(o)
#print(a,b)
a = int(a)
b = int(b)
o[0] = int(o[0])
o[1] = int(o[1])
o[2] = int(o[2])
o[3] = int(o[3])
o[4] = int(o[4])
print("Normalized values:",end='\n')
print((o[0]-a)/(b-a),(o[1]-a)/(b-a),(o[2]-a)/(b-a),(o[3]-a)/(b-a),(o[4]-a)/(b-a),sep='\n')
#res = re.split(",")
#print(f"{res}",sep='\n')