nums_text = input('Enter a series of numbers separated by commas: ')
nums = nums_text.split(',')
m0 = nums[0] = int(nums[0])
m1 = nums[1] = int(nums[1])
m2 = nums[2] = int(nums[2])
m3 = nums[3] = int(nums[3])
m4 = nums[4] = int(nums[4])

_max = max(nums)

print(f'{m0}is the maximum value: {m0 is _max}')
print(f'{m1}is the maximum value: {m1 is _max}')
print(f'{m2}is the maximum value: {m2 is _max}')
print(f'{m3}is the maximum value: {m3 is _max}')
print(f'{m4}is the maximum value: {m4 is _max}')