num_text = input("Enter a series of numbers separated by commas: ")
num = num_text.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])

minNum = min(num)
maxNum = max(num)

r1 = (num[0] - minNum)/(maxNum - minNum)
r2 = (num[1] - minNum)/(maxNum - minNum)
r3 = (num[2] - minNum)/(maxNum - minNum)
r4 = (num[3] - minNum)/(maxNum - minNum)
r5 = (num[4] - minNum)/(maxNum - minNum)

print("Normalized values: ")
print("%.2f" % r1)
print("%.2f" % r2)
print("%.2f" % r3)
print("%.2f" % r4)
print("%.2f" % r5)