nums_text = str(input("Enter a series of numbers separated by commas:"))
nums = nums_text.split(",")
num_min = min(nums) 
num_max = max(nums) 
num_min = int(num_min)
num_max = int(num_max)
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
x_scaled = [(nums[0]-num_min)/(num_max - num_min), (nums[1]-num_min)/(num_max - num_min), (nums[2]-num_min)/(num_max - num_min), 
            (nums[3]-num_min)/(num_max - num_min), (nums[4]-num_min)/(num_max - num_min)]
print("Normalized values: ")
print("%.2f" % x_scaled[0])
print("%.2f" %x_scaled[1])
print("%.2f" %x_scaled[2])
print("%.2f" %x_scaled[3])
print("%.2f" %x_scaled[4])