x = input("Enter a series of numbers separated by commas: ")
num = x.split(",")
num[0] = int(num[0])
num[1] = int(num[1])
num[2] = int(num[2])
num[3] = int(num[3])
num[4] = int(num[4])
_min = min(num)
_max = max(num)
x0 = (num[0]-_min)/(_max-_min)
x1 = (num[1]-_min)/(_max-_min)
x2= (num[2]-_min)/(_max-_min)
x3 = (num[3]-_min)/(_max-_min)
x4 = (num[4]-_min)/(_max-_min)

print("Normalized values: ")
print(f'{x0 : .2f}')
print(f'{x1 : .2f}')
print(f'{x2 : .2f}')
print(f'{x3 : .2f}')
print(f'{x4 : .2f}')