nums_text=input('Enter a series of numbers separated by commas:')
nums = nums_text.split(",")
nums0 = int(nums[0])
nums1 = int(nums[1])
nums2 = int(nums[2])
nums3 = int(nums[3])
nums4 = int(nums[4])
x_max = max(nums0,nums1,nums2,nums3,nums4)
y0 = (nums0 == x_max )
y1 = (nums1 == x_max )
y2 = (nums2 == x_max )
y3 = (nums3 == x_max )
y4 = (nums4 == x_max )
print(nums0,'is the maximum value:',y0)
print(nums1,'is the maximum value:',y1)
print(nums2,'is the maximum value:',y2)
print(nums3,'is the maximum value:',y3)
print(nums4,'is the maximum value:',y4)