nums_text = input("Enter a series of numbers separated by commas:")
nums = nums_text.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])
_max = max(nums)
print(nums[0] ,"is the maximum value:" ,_max is nums[0])
print(nums[1] ,"is the maximum value:" ,_max is nums[1])
print(nums[2] ,"is the maximum value:" ,_max is nums[2])
print(nums[3] ,"is the maximum value:" ,_max is nums[3])
print(nums[4] ,"is the maximum value:" ,_max is nums[4])