nums_text=input("Enter a series of numbers separated by commas:")
nums=nums_text.split(",")
nums[0]=int(nums[0])
nums[1]=int(nums[1])
nums[2]=int(nums[2])
nums[3]=int(nums[3])
nums[4]=int(nums[4])
_min=min(nums)
_max=max(nums)
x1=int(nums[0]-_min)/(_max-_min)
x2=int(nums[1]-_min)/(_max-_min)
x3=int(nums[2]-_min)/(_max-_min)
x4=int(nums[3]-_min)/(_max-_min)
x5=int(nums[4]-_min)/(_max-_min)
print("Normalized values:")
print("%.2f"%x1)
print("%.2f"%x2)
print("%.2f"%x3)
print("%.2f"%x4)
print("%.2f"%x5)