x = input("Enter a series of numbers separated by commas:")

nums = x.split(",")
nums[0] = int(nums[0])
nums[1] = int(nums[1])
nums[2] = int(nums[2])
nums[3] = int(nums[3])
nums[4] = int(nums[4])

slope0 = (nums[0]-min(nums))/(max(nums)-min(nums))
slope1 = (nums[1]-min(nums))/(max(nums)-min(nums))
slope2 = (nums[2]-min(nums))/(max(nums)-min(nums))
slope3 = (nums[3]-min(nums))/(max(nums)-min(nums))
slope4 = (nums[4]-min(nums))/(max(nums)-min(nums))

print("Normalized values:")
print(f"{slope0: .2f}" )
print(f"{slope1: .2f}" )
print(f"{slope2: .2f}" )
print(f"{slope3: .2f}" )
print(f"{slope4: .2f}" )