data = input()
a, b = map(int, data.split(','))

print(f"{a}+{b}={a + b}")
print(f"{a}-{b}={a - b}")
print(f"{a}*{b}={a * b}")
print(f"{a}/{b}={a / b}")
print(f"{a}//{b}={a // b}")
print(f"{a}%{b}={a % b}")
print(f"{a}**{b}={a ** b}")