a= input().split(',')
print((a[0]),'+',(a[1]),'=',int(a[0])+int(a[1]))
print((a[0]),'-',(a[1]),'=',int(a[0])-int(a[1]))
print((a[0]),'*',(a[1]),'=',int(a[0])*int(a[1]))
print((a[0]),'/',(a[1]),'=',int(a[0])/int(a[1]))
print((a[0]),'//',(a[1]),'=',int(a[0])//int(a[1]))
print((a[0]),'%',(a[1]),'=',int(a[0])%int(a[1]))
print((a[0]),'**',(a[1]),'=',int(a[0])**int(a[1]))