x,y = input().split(",")
print(x,'+',y,'=',int(x)+int(y))
print(x,'-',y,'=',int(x)-int(y))
print(x,'*',y,'=',int(x)*int(y))
print(x,'/',y,'=',float(x)/float(y))
print(x,'//',y,'=',int(x)//int(y))
print(x,'%',y,'=',int(x)%int(y))
print(x,'**',y,'=',int(x)**int(y))