ap1 = str(input("Enter item 1 :"))
w1 = float(input("Enter weight 1 : "))
ap2 = str(input("Enter item 2 :"))
w2 = float(input("Enter weight 2 : "))
ap3 = str(input("Enter item 3 :"))
w3= float(input("Enter weight 3 : "))
ap4 = str(input("Enter item 4 :"))
w4 = float(input("Enter weight 4 : "))
total = w1 + w2 + w3 + w4
print(ap1,"           ""%.2f"%w1)
print(ap2,"           ""%.2f"%w2)
print(ap3,"           ""%.2f"%w3)
print(ap4,"           ""%.2f"%w4)
print("---------------------------")
print("Total                     ""%.2f"%total)