Enteritem1 = input("Enter item 1 : ")
Enterweight1 = float(input("Enter weight 1 : "))
Enteritem2 = input("Enter item 2 : ")
Enterweight2 = float(input("Enter weight 2 : "))
Enteritem3 = input("Enter item 3 : ")
Enterweight3 = float(input("Enter weight 3 : "))
Enteritem4 = input("Enter item 4 : ")
Enterweight4 = float(input("Enter weight 4 : "))
print(f"{Enteritem1}           {Enterweight1:.2f}")
print(f"{Enteritem2}           {Enterweight2:.2f}")
print(f"{Enteritem3}           {Enterweight3:.2f}")
print(f"{Enteritem4}           {Enterweight4:.2f}")
print("---------------------------  ")
print(f"total                       {(Enterweight1+Enterweight2+Enterweight3+Enterweight4):.2f}")