item_1 = input("Enter item 1 :  ")
w1 = float(input("Enter weight 1 : "))
item_2 = input("Enter item 2 : ")
w2 = float(input("Enter weight 2 : "))
item_3 = input("Enter item 3 : ")
w3 = float(input("Enter weight 3 : "))
item_4 = input("Enter item 4 : ")
w4 = float(input("Enter weight 4 : "))
print(item_1,f"          {w1:.2f}")
print(item_2,f"          {w2:.2f}")
print(item_3,f"          {w3:.2f}")
print(item_4,f"          {w4:.2f}")
print("---------------------------")
w_all = w1+w2+w3+w4
print(f"total          {w_all:.2f} ")