item1 = input('Enter item 1 :')
item_w1 = float(input("Enter weight 1 :"))
item2 = input('Enter item 2 :')
item_w2 = float(input("Enter weight 2 :"))
item3 = input('Enter item 3 :')
item_w3 = float(input("Enter weight 3 :"))
item4 = input('Enter item 4 :')
item_w4 = float(input("Enter weight 4 :"))
total = item_w1 + item_w2 + item_w3 + item_w4
total = "%.2f" % total
print(item1,'       %.2f'%item_w1)
print(item2,'       %.2f'%item_w2)
print(item3,'       %.2f'%item_w3)
print(item4,'       %.2f'%item_w4)
print("---------------------------")
print("total",'       ',total)