f1 = input("Enter item 1 : ")
w1 = float(input("Enter weight 1 : "))
f2 = input("Enter item 2 : ")
w2 = float(input("Enter weight 2 : "))
f3 = input("Enter item 3 : ")
w3 = float(input("Enter weight 3 : "))
f4 = input("Enter item 4 : ")
w4 = float(input("Enter weight 4 : "))
total = w1 + w2 + w3 + w4
print(f1,f"      {w1:.2f}")
print(f2,f"      {w2:.2f}")
print(f3,f"      {w3:.2f}")
print(f4,f"      {w4:.2f}")
print("---------------------------")
print(f"Total       {total:.2f}")