q = input("Enter item 1 :")
w = float(input("Enter weight 1 :"))
e = input("Enter item 2 : ")
r = float(input("Enter weight 2 : "))
t = input("Enter item 3 : ")
y = float(input("Enter weight 3 : "))
u = input("Enter item 4 : ")
i = float(input("Enter weight 4 : "))
print(q,f"           {w:.2f}")
print(e,f"          {r:.2f}")
print(t,f"          {y:.2f}")
print(u,f"          {i:.2f}")
print("---------------------------")
g = w+r+y+i
print(f"total           {g:.2f}")