ex = input("Enter item 1 : ")
w = float(input("Enter weight 1 :"))
ex2 = input("Enter item 2 : ")
w2 = float(input("Enter weight 2 :"))
ex3 = input("Enter item 3 : ")
w3 = float(input("Enter weight 3 :"))
ex4 = input("Enter item 4 : ")
w4 = float(input("Enter weight 4 :"))
x1 = w+w2+w3+w4
print(ex ,"           ""%.2f"%w)
print(ex2,"           ""%.2f"%w2)
print(ex3,"           ""%.2f"%w3)
print(ex4,"           ""%.2f"%w4)
print("---------------------------  ")
print("total""           ""%.2f"%x1)