a1 = str(input("Enter item 1 : "))
b1 = float(input("Enter weight 1 : "))
a2 = str(input("Enter item 2 : "))
b2 = float(input("Enter weight 2 : "))
a3 = str(input("Enter item 3 : "))
b3 = float(input("Enter weight 3 :"))
a4 = str(input("Enter item 4 : "))
b4 = float(input("Enter weight 4 : "))
t = b1+b2+b3+b4
print(a1,"         ""%.2f"%b1)
print(a2,"         ""%.2f"%b2)
print(a3,"         ""%.2f"%b3)
print(a4,"         ""%.2f"%b4)
print("---------------------------  ")
print("total                    ""%.2f"%t)