x=input("Enter item 1 : ")
y=float(input("Enter weight 1 : "))
x2=input("Enter item 2 : ")
y2=float(input("Enter weight 2 : "))
x3=input("Enter item 3 : ")
y3=float(input("Enter weight 3 : "))
x4=input("Enter item 4 : ")
y4=float(input("Enter weight 4 : "))

print(x,f"           {y:.2f}")
print(x2,f"          {y2:.2f}")
print(x3,f"          {y3:.2f}")
print(x4,f"          {y4:.2f}")
print("---------------------------")
T=y+y2+y3+y4
print(f"total           {T:.2f}")