a = input("Enter item 1 :")
b = float(input("Enter weight 1 :"))
c = input("Enter item 2 :")
d = float(input("Enter weight 2 :"))
e = input("Enter item 3 :")
f = float(input("Enter weight 3 :"))
g = input("Enter item 4 :")
h = float(input("Enter weight 4 :"))
total = b + d + f + h
print(a,f"          {b:.2f}")
print(c,f"                   {d:.2f}")
print(e,f"                        {f:.2f}")
print(g,f"                    {h:.2f}")
print("---------------------------")
print(f"Total                     {total:.2f}")