a1 = input("Enter item 1 : ")
b1 = float(input("Enter weight 1 :"))
a2 = input("Enter item 2 : ")
b2 = float(input("Enter weight 2 :"))
a3 = input("Enter item 3 : ")
b3 = float(input("Enter weight 3 :"))
a4 = input("Enter item 4 : ")
b4 = float(input("Enter weight 4 :"))

print(f"{a1}    {b1:.2f}")
print(f"{a2}    {b2:.2f}")
print(f"{a3}    {b3:.2f}")
print(f"{a4}    {b4:.2f}")
print("---------------------------")
print(f"total   {b1+b2+b3+b4:.2f}")