w1 = input('Enter item 1 :')
f1 = float(input('Enter weight 1 :'))
w2 = input('Enter item 2 :')
f2 = float(input('Enter weight 2 :'))
w3 = input('Enter item 3 :')
f3 = float(input('Enter weight 3 :'))
w4 = input('Enter item 4 :')
f4 = float(input('Enter weight 4 :'))
sp = "      "
print(w1,sp,"%.2f"%f1)
print(w2,sp,"%.2f"%f2)
print(w3,sp,"%.2f"%f3)
print(w4,sp,"%.2f"%f4)
print('---------------------------')
print('Total',sp,"%.2f"%(f1+f2+f3+f4))