a = input("Enter item 1 : ")
weight1 = float(input("Enter weight 1 : "))
b = input("Enter item 2 : ")
weight2 = float(input("Enter weight 2 : "))
c = input("Enter item 3 : ")
weight3 = float(input("Enter weight 3 : "))
d = input("Enter item 4 : ")
weight4 = float(input("Enter weight 4 : "))
total = weight1 + weight2 + weight3 + weight4
print(f"{a:<15}{weight1:.2f}")
print(f"{b:<15}{weight2:.2f}")
print(f"{c:<15}{weight3:.2f}")
print(f"{d:<15}{weight4:.2f}")
print("---------------------------")
print(f"{"total":<15}{total:.2f}")