a=input("Enter item   1 : ")
b=float(input("Enter weight 1 : "))
c=input("Enter item   2 : ")
d=float(input("Enter weight 2 : "))
e=input("Enter item   3 : ")
f=float(input("Enter weight 3 : "))
g=input("Enter item   4 : ")
h=float(input("Enter weight 4 : "))
kee=b+d+f+h
print(f"{a}{b:.2f}")
print(f"{c}{d:.2f}")
print(f"{e}{f:.2f}")
print(f"{g}{h:.2f}")
print("---------------------------")
print(f"{'total'}{kee:.2f}")