f1 = input("Enter item 1 : ")
f1w = float(input("Enter weight 1 : "))
f2 = input("Enter item 2 : ")
f2w = float(input("Enter weight 2 : "))
f3 = input("Enter item 3 : ")
f3w = float(input("Enter weight 3 : "))
f4 = input("Enter item 4 : ")
f4w = float(input("Enter weight 4 : "))

print(f1, f"           {f1w:.2f}")
print(f2, f"           {f2w:.2f}")
print(f3, f"           {f3w:.2f}")
print(f4, f"           {f4w:.2f}")
print("---------------------------")
r = f1w+f2w+f3w+f4w
print("total           ", f"{r:.2f}")