it_1 = str(input("Enter item 1 : "))
we_1 = float(input("Enter weight 1 : "))
it_2 = str(input("Enter item 2 : "))
we_2 = float(input("Enter weight 2 : "))
it_3 = str(input("Enter item 3 : "))
we_3 = float(input("Enter weight 3 : "))
it_4 = str(input("Enter item 4 : "))
we_4 = float(input("Enter weight 4 : "))
totol = we_1 + we_2 + we_3 + we_4
print(it_1,(f"           {we_1:.2f}"))
print(it_2,(f"           {we_2:.2f}"))
print(it_3,(f"           {we_3:.2f}"))
print(it_4,(f"           {we_4:.2f}"))
print("---------------------------")
print(f"total           {totol:.2f}")