items1 = str(input("Enter item 1 :"))
weight1 = float(input("Enter weight 1 :"))
items2 = str(input("Enter item 2 :"))
weight2 = float(input("Enter weight 2 :"))
items3 = str(input("Enter item 3 :"))
weight3 = float(input("Enter weight 3 :"))
items4 = str(input("Enter item 4 :"))
weight4 = float(input("Enter weight 4 :"))
total = float(weight1+weight2+weight3+weight4)
print(items1,f"           {weight1:.2f}")
print(items2,f"           {weight2:.2f}")
print(items3,f"           {weight3:.2f}")
print(items4,f"           {weight4:.2f}")
print("---------------------------")
print("total",f"           {total:.2f}")