a1 = input("Enter item 1 :")
b1 = float(input("Enter weight 1 :"))
a2 = input("Enter item 2 :")
b2 = float(input("Enter weight 2 :"))
a3 = input("Enter item 3 :")
b3 = float(input("Enter weight 3 :"))
a4 = input("Enter item 4 :")
b4 = float(input("Enter weight 4 :"))
c = b1+b2+b3+b4
print(a1    ,f":{b1}:.2f")
print(a2    ,f":{b2}:.2f")
print(a3    ,f":{b3}:.2f")
print(a4    ,f":{b4}:.2f")
print('---------------------------')
print("total",f":{c}:.2f")