e1 = input("Enter item 1 : ")
w1 = float(input("Enter weight 1 : "))
e2 = input("Enter item 2 : ")
w2 = float(input("Enter weight 2 : "))
e3 = input("Enter item 3 : ")
w3 = float(input("Enter weight 3 : "))
e4 = input("Enter item 4 : ")
w4 = float(input("Enter weight 4 : "))
print(e1,'%.2f'%w1,sep='           ')
print(e2,'%.2f'%w2,sep='           ')
print(e3,'%.2f'%w3,sep='           ')
print(e4,'%.2f'%w4,sep='           ')
print('---------------------------')
total = w1+w2+w3+w4
print("total           %.2f" %total)