data1 = input("Enter item 1 :")
weight1 = float(input("Enter weight 1 :"))
data2 = input("Enter item 2 :")
weight2 = float(input("Enter weight 2 :"))
data3 = input("Enter item 3 :")
weight3 = float(input("Enter weight 3 :"))
data4 = input("Enter item 4 :")
weight4 = float(input("Enter weight 4 :"))

print(f"{data1}  {weight1:.2f}")
print(f"{data2}  {weight2:.2f}")
print(f"{data3}  {weight3:.2f}")
print(f"{data4}  {weight4:.2f}")
print("---------------------------")
cal = (weight1+weight2+weight3+weight4)
print(f"total           {cal:.2f}")