jun1 = input("Enter item 1 : ")
wei1 = float(input("Enter weight 1 : "))
jun2 = input("Enter item 2 : ")
wei2 = float(input("Enter weight 2 : "))
jun3 = input("Enter item 3 : ")
wei3 = float(input("Enter weight 3 : "))
jun4 = input("Enter item 4 : ")
wei4 = float(input("Enter weight 4 : "))
print(f"{jun1}           {wei1:.2f}")
print(f"{jun2}           {wei2:.2f}")
print(f"{jun3}           {wei3:.2f}")
print(f"{jun4}           {wei4:.2f}")
print("---------------------------")
junto = wei1 + wei2 + wei3 + wei4
print(f"total           {junto:.2f}")