t1=input("Enter item 1 : ")
w1=float(input("Enter weight 1 : "))
t2=input("Enter item 2 : ")
w2=float(input("Enter weight 2 : "))
t3=input("Enter item 3 : ")
w3=float(input("Enter weight 3 : "))
t4=input("Enter item 4 : ")
w4=float(input("Enter weight 4 : "))
#print(f"{t1}           {w1:.2f}\n{t2}          {w2:.2f}\n{t3}          {w3:.2f}\n{t4}          {w4:.2f}")
print(f"{t1}                   {w1:.2f}\n{t2}          {w2:.2f}\n{t3}                        {w3:.2f}\n{t4}                    {w4:.2f}\n---------------------------")
total=w1+w2+w3+w4
print(f"Total           {total:.2f}")