it = (input("Enter item 1 : "))
wt = float(input("Enter weight 1 : "))
it2 = (input("Enter item 2 : "))
wt2 = float(input("Enter weight 2 : "))
it3 = (input("Enter item 3 : "))
wt3 = float(input("Enter weight 3 : "))
it4 = (input("Enter item 4 : "))
wt4 = float(input("Enter weight 4 : "))
print(f"{it}  {wt:.2f}")
print(f"{it2} {wt2:.2f}")
print(f"{it3} {wt3:.2f}")
print(f"{it4} {wt4:.2f}")
print("---------------------------")
total_weight = wt + wt2 + wt3 + wt4
print(f"{'total':<15} {total_weight:.2f}")