num1 = input("Enter item 1 : ")
num2 = float(input("Enter weight 1 : "))
num3 = input("Enter item 2 : ")
num4 = float(input("Enter weight 2 : "))
num5 = input("Enter item 3 : ")
num6 = float(input("Enter weight 3 : "))
num7 = input("Enter item 4 : ")
num8 = float(input("Enter weight 4 : "))
print(f"{num1}           {num2:.2f}")
print(f"{num3}          {num4:.2f}")
print(f"{num5}          {num6:.2f}")
print(f"{num7}          {num8:.2f}")
print("---------------------------")
total_tungmod = ( num2 + num4 + num6 + num8 ) 
print(f"total           {total_tungmod:.2f}" )