Enter_item1 = input("Enter item 1 :")
Enter_weight1 = float(input("Enter weight 1 : "))
Enter_item2 = input("Enter item 2 :")
Enter_weight2 = float(input("Enter weight 2 :"))
Enter_item3  = input("Enter item 3  :")
Enter_weight3 = float(input("Enter weight 3 :"))
Enter_item4 = input("Enter item 4 :")
Enter_weight4 = float(input("Enter weight 4 :"))
print(f"{Enter_item1}              {Enter_weight1 :.2f}")
print(f"{Enter_item2}              {Enter_weight2:.2f}")
print(f"{Enter_item3}              {Enter_weight3:.2f}")
print(f"{Enter_item4}              {Enter_weight4:.2f}")
print("---------------------------")
print(f"total       {Enter_weight1+Enter_weight2+Enter_weight3+Enter_weight4:.2f}")