a_item = input("Enter item 1 :")
a_wight = float(input("Enter weight 1 :"))
p_item = input("Enter item 2 :")
p_wight = float(input("Enter weight 2 :"))
b_item = input("Enter item 3 :")
b_wight = float(input("Enter weight 3 :"))
o_item = input("Enter item 4 :")
o_wight = float(input("Enter weight 4 :"))
print(f"{a_item}           {a_wight:.2f}")
print(f"{p_item}           {p_wight:.2f}")
print(f"{b_item}           {b_wight:.2f}")
print(f"{o_item}           {o_wight:.2f}")
print("---------------------------")
total = (a_wight + p_wight + b_wight + o_wight)
print(f"total          {total:.2f}")