fruit1 = input("Enter item 1 :")
weight1 = float(input("Enter weight 1 :"))
fruit2 = input("Enter item 2 :")
weight2 = float(input("Enter weight 2:"))
fruit3 = input("Enter item 3 :")
weight3 = float(input("Enter weight 3 :"))
fruit4 = input("Enter item 4 :")
weight4 = float(input("Enter weight 4 :"))
total = weight1 + weight2 + weight3 + weight4
print(f"{fruit1} {weight1:.2f}")
print(f"{fruit2} {weight2:.2f}")
print(f"{fruit3} {weight3:.2f}")
print(f"{fruit4} {weight4:.2f}")
print("---------------------------")
print(f"total {total:.2f}")