n1 = input("Enter item 1 :")
w1 = float(input("Enter weight 1 :"))
n2 = input("Enter item 2 :")
w2 = float(input("Enter weight 2 :"))
n3 = input("Enter item 3 :")
w3 = float(input("Enter weight 3 :"))
n4 = input("Enter item 4 :")
w4 = float(input("Enter weight 4 :"))

total = w1 + w2 + w3 + w4
print(f"{n1}           {w1:.2f}")
print(f"{n2}           {w2:.2f}")
print(f"{n3}           {w3:.2f}")
print(f"{n4}           {w4:.2f}")
print("---------------------------  ")
print(f"total           {total:.2f}")