a=str(input("Enter item 1 : "))
w1=float(input("Enter weight 1 : "))
p=str(input("Enter item 2 :"))
w2=float(input("Enter weight 2 :"))
b=str(input("Enter item 3 : "))
w3=float(input("Enter weight 3 :"))
o=str(input("Enter item 4 :"))
w4=float(input("Enter weight 4 :"))

print(a,"           "f'{w1:.2f}')
print(p,"           "f'{w2:.2f}')
print(b,"           "f'{w3:.2f}')
print(o,"           "f'{w4:.2f}')
n= w1+w2+w3+w4
print("---------------------------")
print("total           ",f'{n:.2f}')