n = input("Display multiplication table of? n : ")
a = int(n)
print(a,'x',1,'=',a*1) 
print(a'x',2,'=',a*2) 
print(a,'x',3,'=',a*3) 
print(a,'x',4,'=',a*4) 
print(a,'x',5,'=',a*5) 
print(a,'x',6,'=',a*6)